/** Brand-mark paths for stack chips, via the installed `simple-icons` package.
 * Named ESM imports only, so bundlers tree-shake the other ~3400 icons away.
 * Skills without a brand mark (React Native, EAS Build, REST APIs) are absent
 * here — SkillMark renders a generic monochrome glyph for those instead. */
import {
  siDart,
  siExpo,
  siExpress,
  siFirebase,
  siFlutter,
  siGit,
  siHtml5,
  siInertia,
  siJavascript,
  siLaravel,
  siMysql,
  siNextdotjs,
  siNodedotjs,
  siOpenjdk,
  siPhp,
  siPostgresql,
  siPython,
  siReact,
  siRender,
  siSqlite,
  siSupabase,
  siTailwindcss,
  siTypescript,
  siVercel,
} from 'simple-icons'

export const SKILL_ICON_PATHS: Record<string, string> = {
  Expo: siExpo.path,
  Flutter: siFlutter.path,
  Dart: siDart.path,
  JavaScript: siJavascript.path,
  TypeScript: siTypescript.path,
  React: siReact.path,
  'Tailwind CSS': siTailwindcss.path,
  'HTML/CSS': siHtml5.path,
  Laravel: siLaravel.path,
  PHP: siPhp.path,
  Inertia: siInertia.path,
  Supabase: siSupabase.path,
  PostgreSQL: siPostgresql.path,
  Git: siGit.path,
  Vercel: siVercel.path,
  Render: siRender.path,
  'Next.js': siNextdotjs.path,
  'expo-sqlite': siSqlite.path,
  'Node.js/Express': siNodedotjs.path,
  Express: siExpress.path,
  Java: siOpenjdk.path,
  Python: siPython.path,
  MySQL: siMysql.path,
  Firebase: siFirebase.path,
}
